### ISSUE TITLE
Misc work tracker

### ISSUE THREAD

**Issue by aahnik** [codegasms/flux#77]
rough overview of features targetted to be implemented in this PR

- [x] fix roles decorator leakage (fixed by saur via order of handlers fixing)
- [x] put async await in old missing places

### auth
 - [ ] set expiry date for cookies

### spaces

- [ ] get a full file (fixes #63 )
- [x] make location of  `storage` directory configurable via env var, with default value of `storage` in cwd. Create empty directory if not exists.
- [x] assureFileDoesNotExist must consider whether the file it is looking for is in trash or outside trash
- [x] when we hit /meta/ by id, give space parent (if user is owner)
- [x] when getFile by id, it would return data, if the current requester has access to requested file's parent dir

### users

- [ ] password set/reset with jwt token with limited time validity
- [ ]  allow admin to edit, delete, and create users
- [ ]  allow admin to promote users to higher role
- [ ]  allow admin to allot quotas to users (admin can give quotas, even without users paying for that)

### billing

- [ ] implement billing logic for space quotas, and mod token plans
- [ ] /billing/spaces/quotaID
- [ ] /billing/mods/planID

---

- [ ] paying would add +n month to expiry date
- [ ] can pay for single month, or multiple months (6 or 12) at once

---

- [ ] after payment is success, unlock the paid feature
- [ ] update space quota , and expiry date a plan
- [ ] update modTokensRemaining
- [ ] define coupon codes
- [ ] system to automatically credit mod tokens at start of billing period (when user has multi-month plan)
- [ ] define limit on how much in advance an user can pay ( 1 mo, 6mo, 1 year)

---

### validations

- [ ] class validators, validate all input dtos

### swagger

- [ ] document required validations in input dtos
- [ ] document all input and output dtos
